# Generated by Django 3.2.9 on 2021-11-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='project/')),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
